include: package:workiva_analysis_options/v1.recommended.yaml

analyzer:
  errors:
    type_annotate_public_apis: ignore
    unused_import: warning
    duplicate_import: warning
    missing_required_param: error
    must_call_super: error
  strong-mode:
    implicit-casts: true # Someday it might be nice to turn this off?
  plugins:
    over_react
