name: ap_over_react
version: 1.0.0
authors:
  - Workiva Client Platform Team <cp@workiva.com>
  - Keal Jones
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  over_react: any
dev_dependencies:
  test: ^1.5.2
  dart_dev: ^2.0.2
  dart_style: any
  over_react_format:
    hosted:
      name: over_react_format
      url: https://pub.workiva.org
    version: "^2.0.1"
  build_daemon: ">=1.0.0 <2.0.0"
  build_resolvers: ^1.0.0
  build_runner: ">=1.3.0 <2.0.0"
  build_test: any
  build_web_compilers: ">=1.2.0 <2.0.0"
  over_react_test: ^2.2.0
  over_react_analyzer_plugin_host:
    git:
      url: git@github.com:greglittlefield-wf/git_playground.git
      ref: over_react_analyzer_plugin/master
      path: plugin_hosts/git
