name: ap_over_react
version: 1.0.0
environment:
  sdk: ">=2.7.2 <3.0.0"
dependencies:
  over_react: ^4.1.0
  react: ^6.0.0
dev_dependencies:
  test: ^1.15.7
  dart_dev: ^3.0.0
  dart_style: any
  build_resolvers: any
  build_runner: any
  build_test: any
  build_web_compilers: any
  over_react_test: ^2.11.0
  over_react_format:
    hosted:
      name: over_react_format
      url: https://pub.workiva.org
    version: ^3.0.0
  test_html_builder: ^1.0.2
  workiva_analysis_options: ^1.1.0
