// This file is generated by over_react_format.
// Please see the README for more information: https://github.com/Workiva/over_react_format
import 'dart:async';

import 'package:over_react_format/format_task.dart' as format_task;

Future<Null> main(List<String> arguments) => format_task.main(arguments);