Map<String, String> exerciseTitles = {
  '01': 'Building the toggle component',
  '02': 'Compound Components',
  '03': 'Flexible Compound Components with context',
  '03.1': 'Flexible Compound Components with context (Consumer Validation)',
  '03.2': 'Flexible Compound Components with context (Avoid Unnecessary Re-renders)',
  '04': 'Render Props',
  '05': 'Prop Collections',
  '06': 'Prop Getters',
  '07': 'State Initializers',
  '08': 'State Reducers',
  '09': 'State Reducers (with change types)',
  '10': 'Control Props',
  '10.1': 'Control Props (Flexible getState)',
  '10.2': 'Control Props (onStateChange)',
  '10.3': 'Control Props (State Change Types)',
  '11': 'The Provider Pattern',
  '11.1': 'The Provider Pattern (Validate Consumer Render)',
  '11.2': 'The Provider Pattern (Avoid Unnecessary Re-renders)',
  '11.3': 'The Provider Pattern (Support Render Props)',
  '11.4': 'The Provider Pattern (Compound Components)',
  '12': 'Higher Order Components',
};

List<String> exerciseList = exerciseTitles.keys.toList();
